* Mastermind
  Mastermind es un juego de mesa, de ingenio y reflexión, para dos
  jugadores.

  El objetivo del juego es adivinar la combinación que ha puesto uno
  de los dos jugadores, el juego termina cuando se adivina la
  combinación o cuando se acaban las combinaciones que dependen del
  tablero.

  Para más información visite: [[https://es.wikipedia.org/wiki/Mastermind][Mastermind]]

** Sobre el proyecto

El proyecto nació en una clase de informática como una práctica de
arrays en c++, nuestro profesor nos dio el código inicial
"mastermind.hpp" con algunas funciones void, que nos ahorraban un
montón de trabajo y de explicaciones, por suerte el código está
diseñado para funcionar en Windows y en distribuciones de GNU/Linux.

Por el momento solo puedo decir que compila en las dos plataformas, en
ambos casos he usado Codeblocks para compilar y ejecutar el programa;
por mi experiencia sé que el ejecutable que se genera en Windows
funciona como un programa más pero en Ubuntu no tengo ni idea, aunque
puedo destacar que la terminal que se ejecutar para visualizar el
programa es Xterm.

La última vez que toqué este código fue el año pasado (2018) y ya en su
momento mi profesor me recomendó cambiar un montón de líneas que
aunque funcionaba no eran eficientes, además de corregir algunos bugs.

** Editor

Hasta el verano pasado (2019) el código, por lo menos de c++ lo
editaba con Codeblocks pero actualmente uso Emacs, he observado que
tiene algunos problemas al momento de compilar ya que genera el
archivo compilado pero no tengo idea de como ejecutarlo lo que implica
que no pueda ver el contenido, esto me ha hecho replantear la
situación y volver a Codeblocks que aunque no me gusta es más cómodo
al momento de compilar y ejecutar.

* Footnotes
/Readme hecho con EMACS/
